## Text Processing

Import Library

In [5]:
!pip install demoji

Requirement already satisfied: demoji in /home/danielpepuho/Desktop/Github/Twitter_crawl/.venv/lib/python3.10/site-packages (1.1.0)

In [6]:
import pandas as pd
import nltk
import numpy
import re
import demoji
import nltk
from nltk.tokenize import word_tokenize

In [7]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     /home/danielpepuho/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

Upload Dataset

In [8]:
url = 'https://drive.google.com/uc?id=1pdaeJ0ThUJcuFmrUzeN_U8ZCApG1yBmT'
df_pemilu = pd.read_csv(url)
df_pemilu.head(15)

,ID,Tweets,Tanggal,Lokasi,Bu ratih,Dhafin,Daniel
0,"1,66E+18","Sama dok, saya gerah juga lihat kelakuan yg ja...",27/05/2023 23:55,NaN,-1,-1.0,-1.0
1,"1,66E+18","Otak kotor itu capresmu Ganjar, capres hobby n...",27/05/2023 23:55,NaN,-1,-1.0,-1.0
2,"1,66E+18",Kwalitas Anies memang diatas 2 capres lainnya....,27/05/2023 23:48,NaN,1,1.0,-1.0
3,"1,66E+18","Laaaa enak tooo liatnya, capres no jaim, yang ...",27/05/2023 23:48,NaN,1,1.0,1.0
4,"1,66E+18",Setujuu.. mereka Oligardan ingin capres boneka...,27/05/2023 23:47,NaN,-1,-1.0,-1.0
5,"1,66E+18","Norak lu Den,...apa yang dilakukan Ganjar suda...",27/05/2023 23:47,NaN,-1,-1.0,-1.0
6,"1,66E+18","Bukan siapa Presidennya, melainkan siapa wakil...",27/05/2023 23:45,NaN,-1,1.0,-1.0
7,"1,66E+18",Contoh capres yang gak suka selfie dan posting...,27/05/2023 23:43,NaN,1,1.0,1.0
8,"1,66E+18",Pa Jokowi hanya menyebut 2 nama capres ..yaitu...,27/05/2023 23:41,NaN,-1,-1.0,-1.0
9,"1,66E+18",Media2 nasional dgn nama besar semakin busuk. ...,27/05/2023 23:39,NaN,-1,-1.0,-1.0
10,"1,66E+18",Dari pada capres anda gagal pimpin Jateng,27/05/2023 23:38,NaN,-1,-1.0,-1.0
11,"1,66E+18",Bolehkah oposisi menyiapkan capres? Boleh saja...,27/05/2023 23:35,NaN,0,-1.0,0.0
12,"1,66E+18",SBY mau jadi capres y?,27/05/2023 23:34,NaN,0,0.0,0.0
13,"1,66E+18",Kurang relevan sih dikaitkan dengan sitkon pol...,27/05/2023 23:34,NaN,0,0.0,0.0
14,"1,66E+18",SBY mau maju ya jd capres?,27/05/2023 23:33,NaN,1,0.0,0.0

Case Folding pada Text Dataset

In [9]:
df_pemilu['Tweets'] = df_pemilu['Tweets'].apply(lambda x: x.lower())
df_pemilu.head(15)

,ID,Tweets,Tanggal,Lokasi,Bu ratih,Dhafin,Daniel
0,"1,66E+18","sama dok, saya gerah juga lihat kelakuan yg ja...",27/05/2023 23:55,NaN,-1,-1.0,-1.0
1,"1,66E+18","otak kotor itu capresmu ganjar, capres hobby n...",27/05/2023 23:55,NaN,-1,-1.0,-1.0
2,"1,66E+18",kwalitas anies memang diatas 2 capres lainnya....,27/05/2023 23:48,NaN,1,1.0,-1.0
3,"1,66E+18","laaaa enak tooo liatnya, capres no jaim, yang ...",27/05/2023 23:48,NaN,1,1.0,1.0
4,"1,66E+18",setujuu.. mereka oligardan ingin capres boneka...,27/05/2023 23:47,NaN,-1,-1.0,-1.0
5,"1,66E+18","norak lu den,...apa yang dilakukan ganjar suda...",27/05/2023 23:47,NaN,-1,-1.0,-1.0
6,"1,66E+18","bukan siapa presidennya, melainkan siapa wakil...",27/05/2023 23:45,NaN,-1,1.0,-1.0
7,"1,66E+18",contoh capres yang gak suka selfie dan posting...,27/05/2023 23:43,NaN,1,1.0,1.0
8,"1,66E+18",pa jokowi hanya menyebut 2 nama capres ..yaitu...,27/05/2023 23:41,NaN,-1,-1.0,-1.0
9,"1,66E+18",media2 nasional dgn nama besar semakin busuk. ...,27/05/2023 23:39,NaN,-1,-1.0,-1.0
10,"1,66E+18",dari pada capres anda gagal pimpin jateng,27/05/2023 23:38,NaN,-1,-1.0,-1.0
11,"1,66E+18",bolehkah oposisi menyiapkan capres? boleh saja...,27/05/2023 23:35,NaN,0,-1.0,0.0
12,"1,66E+18",sby mau jadi capres y?,27/05/2023 23:34,NaN,0,0.0,0.0
13,"1,66E+18",kurang relevan sih dikaitkan dengan sitkon pol...,27/05/2023 23:34,NaN,0,0.0,0.0
14,"1,66E+18",sby mau maju ya jd capres?,27/05/2023 23:33,NaN,1,0.0,0.0

Fungi tokenize

In [10]:
def clean_text(text):
    cleaned_text = re.sub(r'[^\w\s]', '', text)
    return cleaned_text

def tokenize_text(text):
    tokens = word_tokenize(text)
    tokens_with_quotes = ['"' + token + '"' for token in tokens]
    return tokens_with_quotes

In [11]:
df_pemilu['Tweets'] = df_pemilu['Tweets'].apply(clean_text)
df_pemilu['Tweets'] = df_pemilu['Tweets'].apply(tokenize_text)
df_pemilu.head(50)

,ID,Tweets,Tanggal,Lokasi,Bu ratih,Dhafin,Daniel
0,"1,66E+18","[""sama"", ""dok"", ""saya"", ""gerah"", ""juga"", ""liha...",27/05/2023 23:55,NaN,-1,-1.0,-1.0
1,"1,66E+18","[""otak"", ""kotor"", ""itu"", ""capresmu"", ""ganjar"",...",27/05/2023 23:55,NaN,-1,-1.0,-1.0
2,"1,66E+18","[""kwalitas"", ""anies"", ""memang"", ""diatas"", ""2"",...",27/05/2023 23:48,NaN,1,1.0,-1.0
3,"1,66E+18","[""laaaa"", ""enak"", ""tooo"", ""liatnya"", ""capres"",...",27/05/2023 23:48,NaN,1,1.0,1.0
4,"1,66E+18","[""setujuu"", ""mereka"", ""oligardan"", ""ingin"", ""c...",27/05/2023 23:47,NaN,-1,-1.0,-1.0
5,"1,66E+18","[""norak"", ""lu"", ""denapa"", ""yang"", ""dilakukan"",...",27/05/2023 23:47,NaN,-1,-1.0,-1.0
6,"1,66E+18","[""bukan"", ""siapa"", ""presidennya"", ""melainkan"",...",27/05/2023 23:45,NaN,-1,1.0,-1.0
7,"1,66E+18","[""contoh"", ""capres"", ""yang"", ""gak"", ""suka"", ""s...",27/05/2023 23:43,NaN,1,1.0,1.0
8,"1,66E+18","[""pa"", ""jokowi"", ""hanya"", ""menyebut"", ""2"", ""na...",27/05/2023 23:41,NaN,-1,-1.0,-1.0
9,"1,66E+18","[""media2"", ""nasional"", ""dgn"", ""nama"", ""besar"",...",27/05/2023 23:39,NaN,-1,-1.0,-1.0
10,"1,66E+18","[""dari"", ""pada"", ""capres"", ""anda"", ""gagal"", ""p...",27/05/2023 23:38,NaN,-1,-1.0,-1.0
11,"1,66E+18","[""bolehkah"", ""oposisi"", ""menyiapkan"", ""capres""...",27/05/2023 23:35,NaN,0,-1.0,0.0
12,"1,66E+18","[""sby"", ""mau"", ""jadi"", ""capres"", ""y""]",27/05/2023 23:34,NaN,0,0.0,0.0
13,"1,66E+18","[""kurang"", ""relevan"", ""sih"", ""dikaitkan"", ""den...",27/05/2023 23:34,NaN,0,0.0,0.0
14,"1,66E+18","[""sby"", ""mau"", ""maju"", ""ya"", ""jd"", ""capres""]",27/05/2023 23:33,NaN,1,0.0,0.0
15,"1,66E+18","[""udah"", ""bisa"", ""lah"", ""jadi"", ""capres""]",27/05/2023 23:27,NaN,0,0.0,0.0
16,"1,66E+18","[""pagi"", ""prof"", ""klo"", ""bisa"", ""di"", ""usulinn...",27/05/2023 23:23,NaN,1,1.0,1.0
17,"1,66E+18","[""berarti"", ""presiden"", ""sekarang"", ""sibuk"", ""...",27/05/2023 23:23,NaN,-1,-1.0,-1.0
18,"1,66E+18","[""sungguh"", ""keterlaluan"", ""kalau"", ""capres"", ...",27/05/2023 23:21,NaN,-1,-1.0,-1.0
19,"1,66E+18","[""punchline"", ""yg"", ""duarr"", ""banget"", ""pak"", ...",27/05/2023 23:13,NaN,1,1.0,0.0
20,"1,66E+18","[""isi"", ""berita"", ""yang"", ""benar"", ""jusuf"", ""w...",27/05/2023 23:12,NaN,0,1.0,1.0
21,"1,66E+18","[""maklum"", ""bae"", ""capres"", ""yg"", ""tdk"", ""puny...",27/05/2023 23:11,NaN,-1,-1.0,-1.0
22,"1,66E+18","[""tapi"", ""semua"", ""capres"", ""sekarang"", ""pada""...",27/05/2023 23:06,NaN,-1,-1.0,-1.0
23,"1,66E+18","[""kita"", ""liat"", ""beneran"", ""lapor"", ""atao"", ""...",27/05/2023 23:06,NaN,-1,-1.0,-1.0
24,"1,66E+18","[""semua"", ""capres"", ""sama"", ""aja"", ""yg"", ""tdk""...",27/05/2023 23:05,NaN,1,0.0,0.0
25,"1,66E+18","[""dari"", ""bocoran2"", ""rapat"", ""kaum"", ""cebong""...",27/05/2023 23:02,NaN,-1,-1.0,-1.0
26,"1,66E+18","[""h"", ""ganjar"", ""pranowo"", ""capres"", ""pilihan""...",27/05/2023 23:02,NaN,1,1.0,1.0
27,"1,66E+18","[""sosok"", ""capres"", ""pilihan"", ""wong"", ""banten""]",27/05/2023 23:01,NaN,1,1.0,1.0
28,"1,66E+18","[""antusias"", ""masyarakat"", ""banten"", ""sambut"",...",27/05/2023 23:00,NaN,1,1.0,1.0
29,"1,66E+18","[""anis"", ""sama"", ""pendukungnya"", ""emang"", ""11""...",27/05/2023 23:00,NaN,-1,-1.0,-1.0
30,"1,66E+18","[""namanya"", ""juga"", ""pencitraan"", ""dalam"", ""is...",27/05/2023 22:59,NaN,-1,-1.0,-1.0
31,"1,66E+18","[""jk"", ""pilpres"", ""2024"", ""hanya"", ""2"", ""capre...",27/05/2023 22:59,NaN,1,1.0,1.0
32,"1,66E+18","[""antusias"", ""masyarakat"", ""nanten"", ""sambut"",...",27/05/2023 22:59,NaN,1,1.0,1.0
33,"1,66E+18","[""bentar"", ""lg"", ""pemiluwuih"", ""org"", ""pd"", ""s...",27/05/2023 22:57,NaN,-1,-1.0,-1.0
34,"1,66E+18","[""sosok"", ""capres"", ""pilihan"", ""wong"", ""banten...",27/05/2023 22:55,NaN,1,1.0,1.0
35,"1,66E+18","[""lha"", ""wong"", ""pada"", ""rusak"", ""jalanekowe"",...",27/05/2023 22:53,NaN,-1,-1.0,-1.0
36,"1,66E+18","[""statemen"", ""paling"", ""mbelgedes"", ""dari"", ""c...",27/05/2023 22:52,NaN,-1,-1.0,-1.0
37,"1,66E+18","[""bisa"", ""jadi"", ""capres"", ""nya"", ""2"", ""orang""...",27/05/2023 22:50,NaN,-1,0.0,-1.0
38,"1,66E+18","[""2"", ""capres"", ""tp"", ""dsna"", ""pak"", ""yusuf"", ...",27/05/2023 22:48,NaN,0,0.0,0.0
39,"1,66E+18","[""yg"", ""model"", ""begini"", ""kok"", ""di"", ""capres...",27/05/2023 22:42,NaN,-1,0.0,0.0
40,"1,66E+18","[""masih"", ""mau"", ""lanjutin"", ""capres"", ""peneru...",27/05/2023 22:41,NaN,-1,-1.0,-1.0
41,"1,66E+18","[""capres"", ""dibuat"", ""2"", ""calon"", ""adalah"", ""...",27/05/2023 22:40,NaN,0,0.0,0.0
42,"1,66E+18","[""disebut"", ""oleh"", ""nazaruddin"", ""meminta"", ""...",27/05/2023 22:39,NaN,-1,-1.0,-1.0
43,"1,66E+18","[""sebaiknya"", ""abang"", ""sbg"", ""pendukung"", ""pa...",27/05/2023 22:37,NaN,1,1.0,1.0
44,"1,66E+18","[""wkkk"", ""gini"", ""kok"", ""di"", ""capres"", ""kan""]",27/05/2023 22:37,NaN,-1,-1.0,-1.0
45,"1,66E+18","[""tiga"", ""capres"", ""dengan"", ""hobi"", ""yang"", ""...",27/05/2023 22:31,NaN,1,1.0,1.0
46,"1,66E+18","[""dan"", ""hanya"", ""di"", ""indonesia"", ""jelang"", ...",27/05/2023 22:26,NaN,-1,-1.0,-1.0
47,"1,66E+18","[""masuk"", ""survei"", ""karena"", ""berpotensi"", ""j...",27/05/2023 22:25,NaN,-1,-1.0,-1.0
48,"1,66E+18","[""kliatan"", ""nya"", ""beda"", ""pilihan"", ""capres""...",27/05/2023 22:23,NaN,0,0.0,0.0
49,"1,66E+18","[""dangkal"", ""sekali"", ""coba"", ""statementnya"", ...",27/05/2023 22:22,NaN,0,-1.0,-1.0

Stemming

In [23]:
%pip install sastrawi

Requirement already satisfied: sastrawi in /home/danielpepuho/Desktop/Github/Twitter_crawl/.venv/lib/python3.10/site-packages (1.0.1)
Note: you may need to restart the kernel to use updated packages.

In [22]:
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

In [12]:
#from nltk.stem import PorterStemmer

In [13]:
#stemmer = PorterStemmer()

In [14]:
# def stemming_text(text):
#     tokens = word_tokenize(text)
#     stemmed_tokens = [stemmer.stem(token) for token in tokens]
#     stemmed_text = ' '.join(stemmed_tokens)
#     return stemmed_text

In [18]:
# # Mengonversi tipe data kolom 'Tweets' menjadi string
# df_pemilu['Tweets'] = df_pemilu['Tweets'].astype(str)
# # Menerapkan stemming pada kolom 'Tweets'
# df_pemilu['Tweets'] = df_pemilu['Tweets'].apply(stemming_text)

In [19]:
# df_pemilu.head(50)

,ID,Tweets,Tanggal,Lokasi,Bu ratih,Dhafin,Daniel
0,"1,66E+18","[ ' `` sama `` ' , ' `` dok `` ' , ' `` saya `...",27/05/2023 23:55,NaN,-1,-1.0,-1.0
1,"1,66E+18","[ ' `` otak `` ' , ' `` kotor `` ' , ' `` itu ...",27/05/2023 23:55,NaN,-1,-1.0,-1.0
2,"1,66E+18","[ ' `` kwalita `` ' , ' `` ani `` ' , ' `` mem...",27/05/2023 23:48,NaN,1,1.0,-1.0
3,"1,66E+18","[ ' `` laaaa `` ' , ' `` enak `` ' , ' `` tooo...",27/05/2023 23:48,NaN,1,1.0,1.0
4,"1,66E+18","[ ' `` setujuu `` ' , ' `` mereka `` ' , ' `` ...",27/05/2023 23:47,NaN,-1,-1.0,-1.0
5,"1,66E+18","[ ' `` norak `` ' , ' `` lu `` ' , ' `` denapa...",27/05/2023 23:47,NaN,-1,-1.0,-1.0
6,"1,66E+18","[ ' `` bukan `` ' , ' `` siapa `` ' , ' `` pre...",27/05/2023 23:45,NaN,-1,1.0,-1.0
7,"1,66E+18","[ ' `` contoh `` ' , ' `` capr `` ' , ' `` yan...",27/05/2023 23:43,NaN,1,1.0,1.0
8,"1,66E+18","[ ' `` pa `` ' , ' `` jokowi `` ' , ' `` hanya...",27/05/2023 23:41,NaN,-1,-1.0,-1.0
9,"1,66E+18","[ ' `` media2 `` ' , ' `` nasion `` ' , ' `` d...",27/05/2023 23:39,NaN,-1,-1.0,-1.0
10,"1,66E+18","[ ' `` dari `` ' , ' `` pada `` ' , ' `` capr ...",27/05/2023 23:38,NaN,-1,-1.0,-1.0
11,"1,66E+18","[ ' `` bolehkah `` ' , ' `` oposisi `` ' , ' `...",27/05/2023 23:35,NaN,0,-1.0,0.0
12,"1,66E+18","[ ' `` sbi `` ' , ' `` mau `` ' , ' `` jadi ``...",27/05/2023 23:34,NaN,0,0.0,0.0
13,"1,66E+18","[ ' `` kurang `` ' , ' `` relevan `` ' , ' `` ...",27/05/2023 23:34,NaN,0,0.0,0.0
14,"1,66E+18","[ ' `` sbi `` ' , ' `` mau `` ' , ' `` maju ``...",27/05/2023 23:33,NaN,1,0.0,0.0
15,"1,66E+18","[ ' `` udah `` ' , ' `` bisa `` ' , ' `` lah `...",27/05/2023 23:27,NaN,0,0.0,0.0
16,"1,66E+18","[ ' `` pagi `` ' , ' `` prof `` ' , ' `` klo `...",27/05/2023 23:23,NaN,1,1.0,1.0
17,"1,66E+18","[ ' `` berarti `` ' , ' `` presiden `` ' , ' `...",27/05/2023 23:23,NaN,-1,-1.0,-1.0
18,"1,66E+18","[ ' `` sungguh `` ' , ' `` keterlaluan `` ' , ...",27/05/2023 23:21,NaN,-1,-1.0,-1.0
19,"1,66E+18","[ ' `` punchlin `` ' , ' `` yg `` ' , ' `` dua...",27/05/2023 23:13,NaN,1,1.0,0.0
20,"1,66E+18","[ ' `` isi `` ' , ' `` berita `` ' , ' `` yang...",27/05/2023 23:12,NaN,0,1.0,1.0
21,"1,66E+18","[ ' `` maklum `` ' , ' `` bae `` ' , ' `` capr...",27/05/2023 23:11,NaN,-1,-1.0,-1.0
22,"1,66E+18","[ ' `` tapi `` ' , ' `` semua `` ' , ' `` capr...",27/05/2023 23:06,NaN,-1,-1.0,-1.0
23,"1,66E+18","[ ' `` kita `` ' , ' `` liat `` ' , ' `` bener...",27/05/2023 23:06,NaN,-1,-1.0,-1.0
24,"1,66E+18","[ ' `` semua `` ' , ' `` capr `` ' , ' `` sama...",27/05/2023 23:05,NaN,1,0.0,0.0
25,"1,66E+18","[ ' `` dari `` ' , ' `` bocoran2 `` ' , ' `` r...",27/05/2023 23:02,NaN,-1,-1.0,-1.0
26,"1,66E+18","[ ' `` h `` ' , ' `` ganjar `` ' , ' `` pranow...",27/05/2023 23:02,NaN,1,1.0,1.0
27,"1,66E+18","[ ' `` sosok `` ' , ' `` capr `` ' , ' `` pili...",27/05/2023 23:01,NaN,1,1.0,1.0
28,"1,66E+18","[ ' `` antusia `` ' , ' `` masyarakat `` ' , '...",27/05/2023 23:00,NaN,1,1.0,1.0
29,"1,66E+18","[ ' `` ani `` ' , ' `` sama `` ' , ' `` penduk...",27/05/2023 23:00,NaN,-1,-1.0,-1.0
30,"1,66E+18","[ ' `` namanya `` ' , ' `` juga `` ' , ' `` pe...",27/05/2023 22:59,NaN,-1,-1.0,-1.0
31,"1,66E+18","[ ' `` jk `` ' , ' `` pilpr `` ' , ' `` 2024 `...",27/05/2023 22:59,NaN,1,1.0,1.0
32,"1,66E+18","[ ' `` antusia `` ' , ' `` masyarakat `` ' , '...",27/05/2023 22:59,NaN,1,1.0,1.0
33,"1,66E+18","[ ' `` bentar `` ' , ' `` lg `` ' , ' `` pemil...",27/05/2023 22:57,NaN,-1,-1.0,-1.0
34,"1,66E+18","[ ' `` sosok `` ' , ' `` capr `` ' , ' `` pili...",27/05/2023 22:55,NaN,1,1.0,1.0
35,"1,66E+18","[ ' `` lha `` ' , ' `` wong `` ' , ' `` pada `...",27/05/2023 22:53,NaN,-1,-1.0,-1.0
36,"1,66E+18","[ ' `` statemen `` ' , ' `` pale `` ' , ' `` m...",27/05/2023 22:52,NaN,-1,-1.0,-1.0
37,"1,66E+18","[ ' `` bisa `` ' , ' `` jadi `` ' , ' `` capr ...",27/05/2023 22:50,NaN,-1,0.0,-1.0
38,"1,66E+18","[ ' `` 2 `` ' , ' `` capr `` ' , ' `` tp `` ' ...",27/05/2023 22:48,NaN,0,0.0,0.0
39,"1,66E+18","[ ' `` yg `` ' , ' `` model `` ' , ' `` begini...",27/05/2023 22:42,NaN,-1,0.0,0.0
40,"1,66E+18","[ ' `` masih `` ' , ' `` mau `` ' , ' `` lanju...",27/05/2023 22:41,NaN,-1,-1.0,-1.0
41,"1,66E+18","[ ' `` capr `` ' , ' `` dibuat `` ' , ' `` 2 `...",27/05/2023 22:40,NaN,0,0.0,0.0
42,"1,66E+18","[ ' `` disebut `` ' , ' `` oleh `` ' , ' `` na...",27/05/2023 22:39,NaN,-1,-1.0,-1.0
43,"1,66E+18","[ ' `` sebaiknya `` ' , ' `` abang `` ' , ' ``...",27/05/2023 22:37,NaN,1,1.0,1.0
44,"1,66E+18","[ ' `` wkkk `` ' , ' `` gini `` ' , ' `` kok `...",27/05/2023 22:37,NaN,-1,-1.0,-1.0
45,"1,66E+18","[ ' `` tiga `` ' , ' `` capr `` ' , ' `` denga...",27/05/2023 22:31,NaN,1,1.0,1.0
46,"1,66E+18","[ ' `` dan `` ' , ' `` hanya `` ' , ' `` di ``...",27/05/2023 22:26,NaN,-1,-1.0,-1.0
47,"1,66E+18","[ ' `` masuk `` ' , ' `` survei `` ' , ' `` ka...",27/05/2023 22:25,NaN,-1,-1.0,-1.0
48,"1,66E+18","[ ' `` kliatan `` ' , ' `` nya `` ' , ' `` bed...",27/05/2023 22:23,NaN,0,0.0,0.0
49,"1,66E+18","[ ' `` dangkal `` ' , ' `` sekali `` ' , ' `` ...",27/05/2023 22:22,NaN,0,-1.0,-1.0